--[[
    @Framework
    ```
         ___ ___ ___ ___ ___ ___ ___ ___ ___ ___ ___ ___ ___ ___ ___ ___ ___ ___ ___ ___ ___ ___ ___ 
        |___|___|___|___|___|___|___|___|___|___|___|___|___|___|___|___|___|___|___|___|___|___|___|
                                                                                                    
                                                                                                    
         _                                                                                       _   
        | |                     _____                   _   _                                   | |  
        | |                    |  _  |___ ___ _____ ___| |_| |_ ___ _ _ ___                     | |  
        | |                    |   __|  _| . |     | -_|  _|   | -_| | |_ -|                    | |  
        | |                    |__|  |_| |___|_|_|_|___|_| |_|_|___|___|___|                    | |  
        |_|                                                                                     |_|  
         _                                                                                       _   
        | |            _____     _   _            _____                                 _       | |  
        | |     ___   | __  |___| |_| |___ _ _   |   __|___ ___ _____ ___ _ _ _ ___ ___| |_     | |  
        | |    | .'|  |    -| . | . | | . |_'_|  |   __|  _| .'|     | -_| | | | . |  _| '_|    | |  
        | |    |__,|  |__|__|___|___|_|___|_,_|  |__|  |_| |__,|_|_|_|___|_____|___|_| |_,_|    | |  
        |_|                                                                                     |_|  
         _                                                                                       _   
        | |                           _        _          _____     _                           | |  
        | |               _____ ___ _| |___   | |_ _ _   |  |  |___|_|___ ___ ___               | |  
        | |              |     | .'| . | -_|  | . | | |  |    -| .'| |  _| . |_ -|              | |  
        | |              |_|_|_|__,|___|___|  |___|_  |  |__|__|__,|_|_| |___|___|              | |  
        |_|                                       |___|                                         |_|  
                                                                                                    
                                                                                                    
         ___ ___ ___ ___ ___ ___ ___ ___ ___ ___ ___ ___ ___ ___ ___ ___ ___ ___ ___ ___ ___ ___ ___ 
        |___|___|___|___|___|___|___|___|___|___|___|___|___|___|___|___|___|___|___|___|___|___|___|
    ```

    @Description Loads client modules when the server sends a loading packet.

    @NOTE Modules are required sequentially, then initialized sequentially.
    @NOTE This is the listener for the framework's main script, the bootstrapper.
]]
--!strict
--!optimize 2


--[[ @section Imports ]]
local ReplicatedStorage = game:GetService("ReplicatedStorage")
local StarterPlayer = game:GetService("StarterPlayer")
local StarterPlayerScripts = StarterPlayer.StarterPlayerScripts

local SideInitialization = require(ReplicatedStorage.StartupLibs.SideInitialization)

local LoadClientNamespace = require(ReplicatedStorage.Networking.Namespaces.LoadClient)


local ClientComponents = StarterPlayerScripts.ClientComponents

local ChatComponent = ClientComponents.ChatComponent
local UIConnectionsComponent = ClientComponents.UIConnectionsComponent
local FlyComponent = ClientComponents.FlyComponent
local PermissionsDisplayComponent = ClientComponents.PermissionsDisplayComponent
--[[ @section Imports ]]


local ClientModules: { ModuleScript }
= {
    ChatComponent,
    UIConnectionsComponent,
    FlyComponent,
    PermissionsDisplayComponent
}


-- Initialize the client modules once the server sends a loading packet.
LoadClientNamespace.packets.LoadClientModules.listenOnce(function(data: string, player: Player?) SideInitialization(ClientModules) end)